version: '3'
services:
  apache:
    build: .docker/apache
    container_name: sf3_apache
    ports:
      - 9080:80
      - 9443:443
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf3
    depends_on:
      - php

  mysql:
    image: mysql
    container_name: sf3_mysql
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testvideo
      MYSQL_USER: testvideo
      MYSQL_PASSWORD: testvideo

  php:
    build: .docker/php
    container_name: sf3_php
    volumes:
      - .:/home/wwwroot/sf3
    environment:
      - maildev_host=sf3_maildev
    depends_on:
      - maildev
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf3_phpmyadmin
    ports:
      - 9081:80
    links:
      - mysql
      - apache

  maildev:
    image: djfarrelly/maildev
    container_name: sf3_maildev
    ports:
      - 8001:80
