version: "3.7"

services:
    php-apache:
        build: .docker/php-apache
        container_name: php-apache
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
            - writabledata
        links:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
          - 3336:3306
          - 33360:33060
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: project-db
            MYSQL_USER: user
            MYSQL_PASSWORD: password

    writabledata:
        image: busybox:glibc
        volumes:
            - symfonycache:/var/www/var/cache
            - symfonylogs:/var/www/var/logs

volumes:
    symfonycache:
    symfonylogs:
