site_devel_video:
    resource: "@SiteDevelVideoBundle/Controller/"
    type:     annotation
    prefix:   /api

site_devel_user:
    resource: "@SiteDevelUserBundle/Resources/config/routing.yml"
    prefix:   /
