fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

site_devel_user:
    resource: "@SiteDevelUserBundle/Resources/config/routing.yml"
    prefix:   /

site_devel_video:
    resource: "@SiteDevelVideoBundle/Controller/"
    type:     annotation
    prefix:   /api


site_devel_video_api:
    resource: "@SiteDevelVideoBundle/Resources/config/api_routing_v1.yml"
    prefix: /api
    defaults:
        _format: json

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api-doc
