site_devel_video_api:
    resource: "@SiteDevelVideoApiBundle/Controller/"
    type:     annotation
    prefix:   /api

site_devel_video:
    resource: "@SiteDevelVideoBundle/Resources/config/routing.yml"
    prefix:   /

site_devel_user:
    resource: "@SiteDevelUserBundle/Resources/config/routing.yml"
    prefix:   /
